name: Update university dates

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  get-dates:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Fetch latest university dates
        run: node ./.github/workflows/fetchUniDates.js

      - name: Move holidays.json and semesters.json to $lib
        run: |
          mv holidays.json ./src/lib/holidays.json
          mv semesters.json ./src/lib/semesters.json

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ./src/lib/holidays.json
          git add ./src/lib/semesters.json
          git diff --cached --quiet || (git commit -m "cicd: automatically update holidays.json and semesters.json" && git push)
      - name: Push changes
        uses: ad-m/github-push-action@master
