name: Update holidays.json

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  get-holidays:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Fetch latest holidays
        run: node ./.github/workflows/fetchHolidays.js

      - name: Move holidays.json to $lib
        run: |
          mv holidays.json ./src/lib/holidays.json

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add ./src/lib/holidays.json
          git diff --cached --quiet || (git commit -m "Automatically update holidays.json" && git push)
